2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_setup.py:_flush():68] Current SDK version is 0.19.3
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_setup.py:_flush():68] Configure stats pid to 853264
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_setup.py:_flush():68] Loading settings from /home/vfourel/.config/wandb/settings
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_setup.py:_flush():68] Loading settings from /lustre/home/vfourel/SOCProject/SOCmapping/FoundationalModels/wandb/settings
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_init.py:_log_setup():598] Logging user logs to /lustre/home/vfourel/SOCProject/SOCmapping/FoundationalModels/wandb/run-20250114_215902-htjb906s/logs/debug.log
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_init.py:_log_setup():599] Logging internal logs to /lustre/home/vfourel/SOCProject/SOCmapping/FoundationalModels/wandb/run-20250114_215902-htjb906s/logs/debug-internal.log
2025-01-14 21:59:02,610 INFO    MainThread:853264 [wandb_init.py:init():714] calling init triggers
2025-01-14 21:59:02,611 INFO    MainThread:853264 [wandb_init.py:init():719] wandb.init called with sweep_config: {}
config: {}
2025-01-14 21:59:02,611 INFO    MainThread:853264 [wandb_init.py:init():745] starting backend
2025-01-14 21:59:03,131 INFO    MainThread:853264 [wandb_init.py:init():749] sending inform_init request
2025-01-14 21:59:03,216 INFO    MainThread:853264 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-14 21:59:03,217 INFO    MainThread:853264 [wandb_init.py:init():764] backend started and connected
2025-01-14 21:59:03,220 INFO    MainThread:853264 [wandb_init.py:init():857] updated telemetry
2025-01-14 21:59:03,341 INFO    MainThread:853264 [wandb_init.py:init():889] communicating run to backend with 90.0 second timeout
2025-01-14 21:59:03,629 ERROR   MainThread:853264 [wandb_init.py:init():918] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-14 21:59:03,630 ERROR   MainThread:853264 [wandb_init.py:init():1378] error in wandb.init()
Traceback (most recent call last):
  File "/home/vfourel/miniforge3/envs/spectralgpt/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1368, in init
    return wi.init(run_settings)
  File "/home/vfourel/miniforge3/envs/spectralgpt/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 924, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-14 21:59:03,643 WARNING MsgRouterThr:853264 [router.py:message_loop():75] message_loop has been closed
